Any database query is made more useful when the results are sorted and paginated.
With any dynamic finder, beyond the arguments required by the properties/comparators used,
an additional `Map` argument can be added to manage sorting and pagination. (This argument
map is the same used for the `list()` method.)

To sort results as part of your query, use `sort` and `order`.

* `sort` specifies the property to use to sort all instances.
* `order` is a string that specifies whether the sort should be ascending/increasing (`asc`) or
  descending/decreasing (`desc`).

To paginate results as part of your query, use `offset` and `max`.

* `offset` specifies the index of the first result to return.
* `max` specifies the maximum number of results to return.

Pagination parameters are applied *after* sorting parameters.

As an example, let's say I want to find all strategy games supporting at least two players.
[source,groovy]
----
    def games = Game.findAllByStrategyAndMinPlayers(true, 2)
----

Now let's modify that to order the results, showing first the games supporting the highest
maximum number of players. Since we're changing the ordering (and not the conditions to be
included in the results), we add `sort`/`order` query parameters.
[source,groovy]
----
    def games = Game.findAllByStrategyAndMinPlayers(true, 2, [sort: 'maxPlayers', order: 'desc'])
----

Next, let's just show the first group of ten results. Add `offset`/`max` parameters.
[source,groovy]
----
    def games = Game.findAllByStrategyAndMinPlayers(true, 2, [sort: 'maxPlayers', order: 'desc', offset: 0, max: 10])
----

Finally, assuming a user of the application clicked the `Next` button, we can modify the
last call to show the second group of ten results.
[source,groovy]
----
    def games = Game.findAllByStrategyAndMinPlayers(true, 2, [sort: 'maxPlayers', order: 'desc', offset: 10, max: 10])
----
