package demo

class DemoData {

    static initialize() {
        gameData.each { attrs -> initializeGame attrs }
        playerData.each { attrs -> initializePlayer attrs }
        matchData.each { attrs -> initializeMatch attrs }
    }

    // Data culled from boardgamegeek.com. Ratings have been adjusted for a broader range (for purposes of this demo)
    // but are proportional to their original value.
    private static gameData = [
            [name      : 'Gloomhaven', minPlayers: 1, maxPlayers: 4, aveDuration: 120, rating: 9.2,
             categories: ['Adventure', 'Economic', 'Exploration', 'Fantasy', 'Fighting', 'Miniatures'],
             mechanics : ['Action/Movement Programming', 'Campaign/Battle Card Driven', 'Co-operative Play',
                          'Grid Movement', 'Hand Management', 'Modular Board', 'Simultaneous Action Selection',
                          'Storytelling', 'Variable Player Powers']
            ],
            [name      : 'Star Wars: Rebellion', minPlayers: 2, maxPlayers: 4, aveDuration: 210, rating: 8.0,
             categories: ['Dice', 'Fighting', 'Movies/TV/Radio theme', 'Science Fiction', 'Wargame'],
             mechanics : ['Area Control/Area Influence', 'Area Movement', 'Dice Rolling', 'Hand Management']
            ],
            [name      : 'Power Grid', minPlayers: 2, maxPlayers: 6, aveDuration: 120, rating: 6.8,
             categories: ['Economic', 'Industry/Manufacturing'],
             mechanics : ['Auction/Bidding', 'Route/Network Building']
            ],
            [name      : 'Dominion', minPlayers: 2, maxPlayers: 4, aveDuration: 30, rating: 6.4,
             categories: ['Card Game', 'Medieval'],
             mechanics : ['Card Drafting', 'Deck/Pool Building', 'Hand Management']
            ],
            [name      : 'La Granja', minPlayers: 1, maxPlayers: 4, aveDuration: 105, rating: 6.6,
             categories: ['Economic', 'Farming'],
             mechanics : ['Area Control/Area Influence', 'Dice Rolling', 'Hand Management',
                          'Simultaneous Action Selection', 'Variable Player Powers', 'Worker Placement']
            ],
            [name      : 'The Princes of Florence', minPlayers: 2, maxPlayers: 5, aveDuration: 90, rating: 6.2,
             categories: ['City Building', 'Renaissance'],
             mechanics : ['Auction/Bidding', 'Tile Placement']
            ],
            [name      : 'Small World', minPlayers: 2, maxPlayers: 5, aveDuration: 60, rating: 5.8,
             categories: ['Fantasy', 'Fighting', 'Territory Building'],
             mechanics : ['Area Movement', 'Dice Rolling', 'Variable Player Powers']
            ],
            [name      : 'Fresco', minPlayers: 2, maxPlayers: 4, aveDuration: 60, rating: 5.6,
             categories: ['Renaissance'],
             mechanics : ['Action/Movement Programming', 'Grid Movement', 'Set Collection',
                          'Simultaneous Action Selection']
            ],
            [name      : 'Flash Point: Fire Rescue', minPlayers: 1, maxPlayers: 6, aveDuration: 45, rating: 5.6,
             categories: ['Adventure'],
             mechanics : ['Action Point Allowance System', 'Co-operative Play', 'Dice Rolling', 'Grid Movement',
                          'Pick-up and Deliver', 'Simulation', 'Variable Player Powers']
            ],
            [name      : 'Lost Cities', minPlayers: 2, maxPlayers: 2, aveDuration: 30, rating: 5.4,
             categories: ['Card Game', 'Exploration'],
             mechanics : ['Hand Management', 'Set Collection']
            ],
            [name      : 'Vikings', minPlayers: 2, maxPlayers: 4, aveDuration: 60, rating: 5.6,
             categories: ['Economic', 'Medieval', 'Nautical', 'Territory Building'],
             mechanics : ['Auction/Bidding', 'Tile Placement']
            ],
            [name      : 'Space Hulk', minPlayers: 2, maxPlayers: 4, aveDuration: 45, rating: 6.0,
             categories: ['Fighting', 'Miniatures', 'Science Fiction'],
             mechanics : ['Action Point Allowance System', 'Dice Rolling', 'Grid Movement', 'Modular Board']
            ],
            [name      : 'Runebound', minPlayers: 2, maxPlayers: 4, aveDuration: 150, rating: 6.2,
             categories: ['Adventure', 'Exploration', 'Fantasy'],
             mechanics : ['Deck/Pool Building', 'Dice Rolling', 'Variable Player Powers']
            ],
            [name      : 'Last Night on Earth: The Zombie Game', minPlayers: 2, maxPlayers: 6, aveDuration: 90, rating: 5.0,
             categories: ['Fighting', 'Horror', 'Miniatures', 'Zombies'],
             mechanics : ['Dice Rolling', 'Hand Management', 'Modular Board', 'Partnerships', 'Roll/Spin and Move',
                          'Variable Player Powers']
            ],
            [name      : 'Thunder Alley', minPlayers: 2, maxPlayers: 7, aveDuration: 90, rating: 5.8,
             categories: ['Racing', 'Sports'],
             mechanics : ['Hand Management']
            ],
            [name      : 'Incan Gold', minPlayers: 3, maxPlayers: 8, aveDuration: 20, rating: 4.8,
             categories: ['Adventure', 'Bluffing', 'Exploration'],
             mechanics : ['Press Your Luck', 'Simultaneous Action Selection']
            ],
            [name      : "Witch's Brew", minPlayers: 3, maxPlayers: 5, aveDuration: 45, rating: 5.0,
             categories: ['Bluffing', 'Card Game', 'Fantasy'],
             mechanics : ['Hand Management', 'Simultaneous Action Selection']
            ],
            [name      : 'Tournay', minPlayers: 2, maxPlayers: 4, aveDuration: 45, rating: 5.2,
             categories: ['Card Game', 'City Building', 'Economic', 'Medieval'],
             mechanics : ['Card Drafting', 'Hand Management', 'Worker Placement']
            ],
            [name      : 'Amyitis', minPlayers: 2, maxPlayers: 4, aveDuration: 90, rating: 5.0,
             categories: ['Ancient'],
             mechanics : ['Area Control/Area Influence']
            ],
            [name      : 'Coup: Rebellion G54', minPlayers: 3, maxPlayers: 6, aveDuration: 15, rating: 5.4,
             categories: ['Bluffing', 'Card Game', 'Deduction', 'Negotiation', 'Political'],
             mechanics : ['Player Elimination', 'Take That', 'Variable Player Powers']
            ],
            [name      : 'Havana', minPlayers: 2, maxPlayers: 4, aveDuration: 45, rating: 4.8,
             categories: ['Bluffing', 'Card Game'],
             mechanics : ['Hand Management', 'Memory', 'Set Collection', 'Simultaneous Action Selection']
            ],
            [name      : 'Dead Men Tell No tales', minPlayers: 2, maxPlayers: 5, aveDuration: 75, rating: 5.4,
             categories: ['Exploration', 'Fantasy', 'Fighting', 'Nautical', 'Pirates'],
             mechanics : ['Action Point Allowance System', 'Co-operative Play', 'Dice Rolling', 'Grid Movement',
                          'Modular Board', 'Pick-up and Deliver', 'Variable Player Powers']
            ],
            [name      : "Odin's Ravens", minPlayers: 2, maxPlayers: 2, aveDuration: 30, rating: 4.4,
             categories: ['Animals', 'Card Game', 'Mythology', 'Racing'],
             mechanics : ['Hand Management']
            ],
            [name      : 'SET', minPlayers: 2, maxPlayers: 20, aveDuration: 30, rating: 4.0,
             categories: ['Card Game', 'Puzzle', 'Real-time'],
             mechanics : ['Pattern Recognition', 'Set Collection']
            ],
            [name      : 'Metro', minPlayers: 2, maxPlayers: 6, aveDuration: 30, rating: 3.8,
             categories: ['Trains'],
             mechanics : ['Route/Network Building', 'Tile Placement']
            ],
    ]

    private static playerData = [
            [name   : 'Graeme Rocher',
             library: ["Coup: Rebellion G54",
                       "Havana",
                       "Odin's Ravens",
                       "Star Wars: Rebellion",
                       "Dominion"]
            ],
            [name   : 'Jeff Brown',
             library: ["La Granja",
                       "Lost Cities",
                       "Star Wars: Rebellion",
                       "Small World",
                       "SET",
                       "Havana"]
            ],
            [name   : 'Paul King',
             library: ["Space Hulk",
                       "Gloomhaven",
                       "Tournay",
                       "Witch's Brew",
                       "Star Wars: Rebellion",
                       "Runebound",
                       "Metro",
                       "The Princes of Florence"]
            ],
            [name   : 'Álvaro Sánchez',
             library: ["Incan Gold",
                       "The Princes of Florence",
                       "Metro",
                       "Vikings",
                       "Last Night on Earth: The Zombie Game",
                       "Coup: Rebellion G54",
                       "Flash Point: Fire Rescue",
                       "Runebound"]
            ],
            [name   : 'James Kleeh',
             library: ["Coup: Rebellion G54",
                       "Vikings",
                       "Tournay",
                       "Thunder Alley",
                       "Dead Men Tell No tales"]
            ],
            [name   : 'Dave Klein',
             library: ["Power Grid",
                       "Thunder Alley",
                       "Incan Gold",
                       "Space Hulk",
                       "Small World",
                       "Lost Cities",
                       "Metro"]
            ],
            [name   : 'Colin Harrington',
             library: ["Space Hulk",
                       "SET",
                       "Dead Men Tell No tales",
                       "Havana",
                       "Witch's Brew"]
            ],
            [name   : 'Zachary Klein',
             library: ["Coup: Rebellion G54",
                       "Thunder Alley",
                       "Last Night on Earth: The Zombie Game",
                       "Flash Point: Fire Rescue",
                       "La Granja",
                       "Dead Men Tell No tales"]
            ],
            [name   : 'Jack Frosch',
             library: ["Dominion",
                       "Space Hulk",
                       "Incan Gold",
                       "Thunder Alley",
                       "Odin's Ravens",
                       "Fresco",
                       "SET",
                       "The Princes of Florence",
                       "Flash Point: Fire Rescue",
                       "Lost Cities",
                       "Dead Men Tell No tales",
                       "Vikings",
                       "Coup: Rebellion G54",
                       "Gloomhaven"]
            ],
            [name   : 'Ryan Vanderwerf',
             library: ["La Granja",
                       "Coup: Rebellion G54",
                       "Gloomhaven",
                       "SET",
                       "Star Wars: Rebellion",
                       "Thunder Alley",
                       "Runebound",
                       "Havana"]
            ],
            [name   : 'Ben Rihne',
             library: ["Space Hulk",
                       "Thunder Alley",
                       "Odin's Ravens",
                       "Witch's Brew",
                       "Gloomhaven",
                       "Vikings",
                       "Star Wars: Rebellion",
                       "Small World"]
            ],
            [name   : 'Will Buck',
             library: ["Metro",
                       "Last Night on Earth: The Zombie Game",
                       "Gloomhaven",
                       "SET",
                       "Incan Gold",
                       "Flash Point: Fire Rescue",
                       "Tournay",
                       "Space Hulk",
                       "Dominion"]
            ],
            [name   : 'Sergio del Amo',
             library: ["Dead Men Tell No tales",
                       "La Granja",
                       "Lost Cities",
                       "Tournay",
                       "SET",
                       "Coup: Rebellion G54",
                       "Havana",
                       "Runebound",
                       "Amyitis",
                       "The Princes of Florence",
                       "Incan Gold",
                       "Space Hulk"]
            ],
            [name   : 'Iván López',
             library: ["Amyitis",
                       "Coup: Rebellion G54",
                       "Gloomhaven",
                       "Havana",
                       "SET",
                       "Odin's Ravens",
                       "Lost Cities",
                       "Witch's Brew",
                       "Small World",
                       "Incan Gold",
                       "Vikings",
                       "Dead Men Tell No tales",
                       "Space Hulk"]
            ],
            [name   : 'Matthew Moss',
             library: ["Fresco",
                       "Dead Men Tell No tales",
                       "Small World",
                       "Incan Gold",
                       "Dominion",
                       "The Princes of Florence",
                       "Tournay",
                       "Last Night on Earth: The Zombie Game",
                       "Thunder Alley",
                       "Witch's Brew",
                       "Metro",
                       "SET",
                       "Star Wars: Rebellion",
                       "Gloomhaven"]
            ],
            [name   : 'Nirav Assar',
             library: ["Small World",
                       "Tournay",
                       "Space Hulk",
                       "Dead Men Tell No tales",
                       "Fresco",
                       "Havana",
                       "Dominion",
                       "The Princes of Florence",
                       "SET",
                       "Coup: Rebellion G54",
                       "Witch's Brew"]
            ],
    ]

    // Scores in match data are in the range 1-100, but were randomly generated for demo purposes and have no actual
    // correlation to the game played. Match data without a finished date (and corresponding score values) mean the
    // game is ongoing.
    private static matchData = [
            [game   : "The Princes of Florence",
             started: new Date(117, 2, 1, 15, 30),
             scores : [[name: 'Álvaro Sánchez'],
                       [name: 'Will Buck']],
            ],
            [game    : "Amyitis",
             started : new Date(117, 2, 2, 15, 30),
             finished: new Date(117, 2, 2, 17, 2),
             scores  : [[name: 'Jeff Brown', score: 94],
                        [name: 'Iván López', score: 14],
                        [name: 'Colin Harrington', score: 65],
                        [name: 'Ryan Vanderwerf', score: 80]],
            ],
            [game   : "Incan Gold",
             started: new Date(117, 2, 3, 15, 30),
             scores : [[name: 'Graeme Rocher'],
                       [name: 'Sergio del Amo'],
                       [name: 'Ben Rihne'],
                       [name: 'Álvaro Sánchez'],
                       [name: 'Nirav Assar'],
                       [name: 'James Kleeh'],
                       [name: 'Colin Harrington'],
                       [name: 'Matthew Moss']],
            ],
            [game    : "Dominion",
             started : new Date(117, 2, 4, 15, 30),
             finished: new Date(117, 2, 4, 16, 0),
             scores  : [[name: 'Graeme Rocher', score: 26],
                        [name: 'Ryan Vanderwerf', score: 94],
                        [name: 'Nirav Assar', score: 1]],
            ],
            [game    : "Coup: Rebellion G54",
             started : new Date(117, 2, 5, 15, 30),
             finished: new Date(117, 2, 5, 16, 3),
             scores  : [[name: 'Ryan Vanderwerf', score: 71],
                        [name: 'Dave Klein', score: 41],
                        [name: 'Álvaro Sánchez', score: 33],
                        [name: 'Ben Rihne', score: 30],
                        [name: 'Colin Harrington', score: 84],
                        [name: 'James Kleeh', score: 12]],
            ],
            [game    : "Lost Cities",
             started : new Date(117, 2, 6, 15, 30),
             finished: new Date(117, 2, 6, 15, 52),
             scores  : [[name: 'Paul King', score: 33],
                        [name: 'Jeff Brown', score: 23]],
            ],
            [game    : "SET",
             started : new Date(117, 2, 7, 15, 30),
             finished: new Date(117, 2, 7, 16, 13),
             scores  : [[name: 'Paul King', score: 79],
                        [name: 'Ryan Vanderwerf', score: 94],
                        [name: 'Álvaro Sánchez', score: 48],
                        [name: 'Graeme Rocher', score: 42],
                        [name: 'Matthew Moss', score: 31],
                        [name: 'Jeff Brown', score: 36],
                        [name: 'Dave Klein', score: 22],
                        [name: 'Iván López', score: 56],
                        [name: 'Colin Harrington', score: 82],
                        [name: 'Ben Rihne', score: 100],
                        [name: 'Jack Frosch', score: 1],
                        [name: 'Will Buck', score: 52],
                        [name: 'Zachary Klein', score: 43],
                        [name: 'James Kleeh', score: 42],
                        [name: 'Nirav Assar', score: 85],
                        [name: 'Sergio del Amo', score: 97]],
            ],
            [game   : "Incan Gold",
             started: new Date(117, 2, 8, 15, 30),
             scores : [[name: 'Graeme Rocher'],
                       [name: 'Álvaro Sánchez'],
                       [name: 'Nirav Assar'],
                       [name: 'Will Buck'],
                       [name: 'Zachary Klein']],
            ],
            [game    : "Dead Men Tell No tales",
             started : new Date(117, 2, 9, 15, 30),
             finished: new Date(117, 2, 9, 16, 48),
             scores  : [[name: 'Álvaro Sánchez', score: 75],
                        [name: 'Paul King', score: 10],
                        [name: 'Ben Rihne', score: 69],
                        [name: 'Jeff Brown', score: 79],
                        [name: 'Sergio del Amo', score: 89]],
            ],
            [game   : "Coup: Rebellion G54",
             started: new Date(117, 2, 10, 15, 30),
             scores : [[name: 'James Kleeh'],
                       [name: 'Jeff Brown'],
                       [name: 'Nirav Assar'],
                       [name: 'Ben Rihne'],
                       [name: 'Colin Harrington'],
                       [name: 'Iván López']],
            ],
            [game   : "Space Hulk",
             started: new Date(117, 2, 11, 15, 30),
             scores : [[name: 'Nirav Assar'],
                       [name: 'Ben Rihne'],
                       [name: 'Ryan Vanderwerf'],
                       [name: 'Álvaro Sánchez']],
            ],
            [game    : "Space Hulk",
             started : new Date(117, 2, 12, 15, 30),
             finished: new Date(117, 2, 12, 16, 20),
             scores  : [[name: 'James Kleeh', score: 32],
                        [name: 'Álvaro Sánchez', score: 59]],
            ],
            [game    : "Lost Cities",
             started : new Date(117, 2, 13, 15, 30),
             finished: new Date(117, 2, 13, 16, 12),
             scores  : [[name: 'Dave Klein', score: 68],
                        [name: 'Will Buck', score: 100]],
            ],
            [game    : "Power Grid",
             started : new Date(117, 2, 14, 15, 30),
             finished: new Date(117, 2, 14, 17, 37),
             scores  : [[name: 'Colin Harrington', score: 90],
                        [name: 'Iván López', score: 35],
                        [name: 'Jack Frosch', score: 67],
                        [name: 'Matthew Moss', score: 61]],
            ],
            [game    : "Coup: Rebellion G54",
             started : new Date(117, 2, 15, 15, 30),
             finished: new Date(117, 2, 15, 15, 54),
             scores  : [[name: 'Zachary Klein', score: 89],
                        [name: 'Will Buck', score: 19],
                        [name: 'Dave Klein', score: 30],
                        [name: 'James Kleeh', score: 82]],
            ],
            [game    : "Space Hulk",
             started : new Date(117, 2, 16, 15, 30),
             finished: new Date(117, 2, 16, 16, 27),
             scores  : [[name: 'Paul King', score: 14],
                        [name: 'Ryan Vanderwerf', score: 60]],
            ],
            [game    : "Amyitis",
             started : new Date(117, 2, 17, 15, 30),
             finished: new Date(117, 2, 17, 16, 56),
             scores  : [[name: 'Sergio del Amo', score: 97],
                        [name: 'Jack Frosch', score: 81]],
            ],
            [game    : "Havana",
             started : new Date(117, 2, 18, 15, 30),
             finished: new Date(117, 2, 18, 16, 10),
             scores  : [[name: 'Graeme Rocher', score: 22],
                        [name: 'Ben Rihne', score: 33]],
            ],
            [game   : "Gloomhaven",
             started: new Date(117, 2, 19, 15, 30),
             scores : [[name: 'Zachary Klein'],
                       [name: 'Colin Harrington'],
                       [name: 'Sergio del Amo']],
            ],
            [game    : "Tournay",
             started : new Date(117, 2, 20, 15, 30),
             finished: new Date(117, 2, 20, 16, 23),
             scores  : [[name: 'Will Buck', score: 35],
                        [name: 'Ben Rihne', score: 54],
                        [name: 'Nirav Assar', score: 55]],
            ],
            [game   : "Coup: Rebellion G54",
             started: new Date(117, 2, 21, 15, 30),
             scores : [[name: 'Dave Klein'],
                       [name: 'Ryan Vanderwerf'],
                       [name: 'Colin Harrington'],
                       [name: 'Nirav Assar'],
                       [name: 'James Kleeh']],
            ],
            [game    : "Power Grid",
             started : new Date(117, 2, 22, 15, 30),
             finished: new Date(117, 2, 22, 17, 34),
             scores  : [[name: 'Will Buck', score: 100],
                        [name: 'Jeff Brown', score: 47]],
            ],
            [game    : "Coup: Rebellion G54",
             started : new Date(117, 2, 23, 15, 30),
             finished: new Date(117, 2, 23, 15, 41),
             scores  : [[name: 'Paul King', score: 2],
                        [name: 'Matthew Moss', score: 91],
                        [name: 'Zachary Klein', score: 48]],
            ],
            [game    : "Lost Cities",
             started : new Date(117, 2, 24, 15, 30),
             finished: new Date(117, 2, 24, 16, 19),
             scores  : [[name: 'Ben Rihne', score: 34],
                        [name: 'Jeff Brown', score: 75]],
            ],
            [game    : "Lost Cities",
             started : new Date(117, 2, 25, 15, 30),
             finished: new Date(117, 2, 25, 16, 14),
             scores  : [[name: 'Dave Klein', score: 83],
                        [name: 'Matthew Moss', score: 31]],
            ],
            [game   : "Star Wars: Rebellion",
             started: new Date(117, 2, 26, 15, 30),
             scores : [[name: 'Jeff Brown'],
                       [name: 'Ryan Vanderwerf'],
                       [name: 'Jack Frosch'],
                       [name: 'Sergio del Amo']],
            ],
            [game   : "Last Night on Earth: The Zombie Game",
             started: new Date(117, 2, 27, 15, 30),
             scores : [[name: 'Graeme Rocher'],
                       [name: 'Will Buck'],
                       [name: 'Jeff Brown']],
            ],
            [game    : "Thunder Alley",
             started : new Date(117, 2, 28, 15, 30),
             finished: new Date(117, 2, 28, 17, 6),
             scores  : [[name: 'James Kleeh', score: 84],
                        [name: 'Sergio del Amo', score: 78]],
            ],
            [game    : "Havana",
             started : new Date(117, 2, 29, 15, 30),
             finished: new Date(117, 2, 29, 16, 17),
             scores  : [[name: 'Ben Rihne', score: 7],
                        [name: 'Colin Harrington', score: 30],
                        [name: 'Iván López', score: 4],
                        [name: 'Sergio del Amo', score: 30]],
            ],
            [game    : "SET",
             started : new Date(117, 2, 30, 15, 30),
             finished: new Date(117, 2, 30, 15, 59),
             scores  : [[name: 'Dave Klein', score: 23],
                        [name: 'Matthew Moss', score: 79],
                        [name: 'Álvaro Sánchez', score: 44],
                        [name: 'Nirav Assar', score: 95],
                        [name: 'Ben Rihne', score: 92],
                        [name: 'Jeff Brown', score: 60],
                        [name: 'Jack Frosch', score: 69],
                        [name: 'Sergio del Amo', score: 47],
                        [name: 'Colin Harrington', score: 60],
                        [name: 'James Kleeh', score: 91],
                        [name: 'Graeme Rocher', score: 49],
                        [name: 'Ryan Vanderwerf', score: 8],
                        [name: 'Will Buck', score: 28],
                        [name: 'Paul King', score: 34],
                        [name: 'Zachary Klein', score: 60]],
            ],
            [game    : "Last Night on Earth: The Zombie Game",
             started : new Date(117, 2, 31, 15, 30),
             finished: new Date(117, 2, 31, 16, 50),
             scores  : [[name: 'Zachary Klein', score: 10],
                        [name: 'Colin Harrington', score: 88],
                        [name: 'Graeme Rocher', score: 1],
                        [name: 'Ryan Vanderwerf', score: 56],
                        [name: 'Jeff Brown', score: 62]],
            ],
    ]

    static private initializeGame(Map attrs) {
        def info = attrs.collectEntries { it }

        def categories = info.remove('categories')
        def mechanics = info.remove('mechanics')

        def game = new Game(info)
        categories.each { String category ->
            game.addToCategories(Category.findOrSaveByName(category))
        }
        mechanics.each { String mechanic ->
            game.addToMechanics(Mechanic.findOrSaveByName(mechanic))
        }

        game.save flush: true, failOnError: true
    }

    static private initializePlayer(Map attrs) {
        def info = attrs.collectEntries { it }

        def library = info.remove('library')

        def player = new Player(info)
        library.each { String name -> player.addToLibrary(Game.findByName(name)) }

        player.save flush: true, failOnError: true
    }

    static private initializeMatch(Map attrs) {
        def info = attrs.collectEntries { it }

        info.game = Game.findByName(info.remove('game') as String)
        def scores = info.remove('scores')

        def match = new Match(info)
        scores.each { Map scoreInfo ->
            String playerName = scoreInfo.name
            match.addToScores(new Score(player: Player.findByName(playerName), score: scoreInfo.score))
        }

        match.save flush: true, failOnError: true
    }
}